// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// wofost
NumericMatrix wofost(List crop, DataFrame weather, List soil, List control);
RcppExport SEXP _Rwofost_wofost(SEXP cropSEXP, SEXP weatherSEXP, SEXP soilSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type crop(cropSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type weather(weatherSEXP);
    Rcpp::traits::input_parameter< List >::type soil(soilSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(wofost(crop, weather, soil, control));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_wofost();

static const R_CallMethodDef CallEntries[] = {
    {"_Rwofost_wofost", (DL_FUNC) &_Rwofost_wofost, 4},
    {"_rcpp_module_boot_wofost", (DL_FUNC) &_rcpp_module_boot_wofost, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rwofost(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
