# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.wofost <- function(crop, weather, soil, control) {
    .Call('_Rwofost_wofost', PACKAGE = 'Rwofost', crop, weather, soil, control)
}

